
package com.digipay.employee;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PermissionControllerImplService", targetNamespace = "http://impl.controller.digipay.com/", wsdlLocation = "http://localhost:8080/usermanagement/permission?wsdl")
public class PermissionControllerImplService
    extends Service
{

    private final static URL PERMISSIONCONTROLLERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERMISSIONCONTROLLERIMPLSERVICE_EXCEPTION;
    private final static QName PERMISSIONCONTROLLERIMPLSERVICE_QNAME = new QName("http://impl.controller.digipay.com/", "PermissionControllerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/usermanagement/permission?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERMISSIONCONTROLLERIMPLSERVICE_WSDL_LOCATION = url;
        PERMISSIONCONTROLLERIMPLSERVICE_EXCEPTION = e;
    }

    public PermissionControllerImplService() {
        super(__getWsdlLocation(), PERMISSIONCONTROLLERIMPLSERVICE_QNAME);
    }

    public PermissionControllerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERMISSIONCONTROLLERIMPLSERVICE_QNAME, features);
    }

    public PermissionControllerImplService(URL wsdlLocation) {
        super(wsdlLocation, PERMISSIONCONTROLLERIMPLSERVICE_QNAME);
    }

    public PermissionControllerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERMISSIONCONTROLLERIMPLSERVICE_QNAME, features);
    }

    public PermissionControllerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PermissionControllerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PermissionController
     */
    @WebEndpoint(name = "PermissionControllerImplPort")
    public PermissionController getPermissionControllerImplPort() {
        return super.getPort(new QName("http://impl.controller.digipay.com/", "PermissionControllerImplPort"), PermissionController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PermissionController
     */
    @WebEndpoint(name = "PermissionControllerImplPort")
    public PermissionController getPermissionControllerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.controller.digipay.com/", "PermissionControllerImplPort"), PermissionController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERMISSIONCONTROLLERIMPLSERVICE_EXCEPTION!= null) {
            throw PERMISSIONCONTROLLERIMPLSERVICE_EXCEPTION;
        }
        return PERMISSIONCONTROLLERIMPLSERVICE_WSDL_LOCATION;
    }

}
