
package com.digipay.employee;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PermissionController", targetNamespace = "http://controller.digipay.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PermissionController {


    /**
     * 
     * @return
     *     returns java.util.List<com.digipay.employee.Permission>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "displayPermission", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.DisplayPermission")
    @ResponseWrapper(localName = "displayPermissionResponse", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.DisplayPermissionResponse")
    @Action(input = "http://controller.digipay.com/PermissionController/displayPermissionRequest", output = "http://controller.digipay.com/PermissionController/displayPermissionResponse")
    public List<Permission> displayPermission();

    /**
     * 
     * @param name
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "updatePermission", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.UpdatePermission")
    @ResponseWrapper(localName = "updatePermissionResponse", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.UpdatePermissionResponse")
    @Action(input = "http://controller.digipay.com/PermissionController/updatePermissionRequest", output = "http://controller.digipay.com/PermissionController/updatePermissionResponse")
    public void updatePermission(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "removePermission", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.RemovePermission")
    @ResponseWrapper(localName = "removePermissionResponse", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.RemovePermissionResponse")
    @Action(input = "http://controller.digipay.com/PermissionController/removePermissionRequest", output = "http://controller.digipay.com/PermissionController/removePermissionResponse")
    public void removePermission(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @param title
     */
    @WebMethod
    @RequestWrapper(localName = "savePermissionInfo", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.SavePermissionInfo")
    @ResponseWrapper(localName = "savePermissionInfoResponse", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.SavePermissionInfoResponse")
    @Action(input = "http://controller.digipay.com/PermissionController/savePermissionInfoRequest", output = "http://controller.digipay.com/PermissionController/savePermissionInfoResponse")
    public void savePermissionInfo(
        @WebParam(name = "title", targetNamespace = "")
        String title);

}
