
package com.digipay.employee;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "RoleControllerImplService", targetNamespace = "http://impl.controller.digipay.com/", wsdlLocation = "http://localhost:8080/usermanagement/role?wsdl")
public class RoleControllerImplService
    extends Service
{

    private final static URL ROLECONTROLLERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ROLECONTROLLERIMPLSERVICE_EXCEPTION;
    private final static QName ROLECONTROLLERIMPLSERVICE_QNAME = new QName("http://impl.controller.digipay.com/", "RoleControllerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/usermanagement/role?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROLECONTROLLERIMPLSERVICE_WSDL_LOCATION = url;
        ROLECONTROLLERIMPLSERVICE_EXCEPTION = e;
    }

    public RoleControllerImplService() {
        super(__getWsdlLocation(), ROLECONTROLLERIMPLSERVICE_QNAME);
    }

    public RoleControllerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROLECONTROLLERIMPLSERVICE_QNAME, features);
    }

    public RoleControllerImplService(URL wsdlLocation) {
        super(wsdlLocation, ROLECONTROLLERIMPLSERVICE_QNAME);
    }

    public RoleControllerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROLECONTROLLERIMPLSERVICE_QNAME, features);
    }

    public RoleControllerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RoleControllerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RoleController
     */
    @WebEndpoint(name = "RoleControllerImplPort")
    public RoleController getRoleControllerImplPort() {
        return super.getPort(new QName("http://impl.controller.digipay.com/", "RoleControllerImplPort"), RoleController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RoleController
     */
    @WebEndpoint(name = "RoleControllerImplPort")
    public RoleController getRoleControllerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.controller.digipay.com/", "RoleControllerImplPort"), RoleController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROLECONTROLLERIMPLSERVICE_EXCEPTION!= null) {
            throw ROLECONTROLLERIMPLSERVICE_EXCEPTION;
        }
        return ROLECONTROLLERIMPLSERVICE_WSDL_LOCATION;
    }

}
