
package com.digipay.employee;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "RoleController", targetNamespace = "http://controller.digipay.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RoleController {


    /**
     * 
     * @param permissionId
     * @param roleTitle
     */
    @WebMethod
    @RequestWrapper(localName = "saveRoleInfo", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.SaveRoleInfo")
    @ResponseWrapper(localName = "saveRoleInfoResponse", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.SaveRoleInfoResponse")
    @Action(input = "http://controller.digipay.com/RoleController/saveRoleInfoRequest", output = "http://controller.digipay.com/RoleController/saveRoleInfoResponse")
    public void saveRoleInfo(
        @WebParam(name = "roleTitle", targetNamespace = "")
        String roleTitle,
        @WebParam(name = "permissionId", targetNamespace = "")
        List<String> permissionId);

    /**
     * 
     * @return
     *     returns java.util.List<com.digipay.employee.Role>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "displayUserRole", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.DisplayUserRole")
    @ResponseWrapper(localName = "displayUserRoleResponse", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.DisplayUserRoleResponse")
    @Action(input = "http://controller.digipay.com/RoleController/displayUserRoleRequest", output = "http://controller.digipay.com/RoleController/displayUserRoleResponse")
    public List<Role> displayUserRole();

    /**
     * 
     * @param name
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "updateUserRole", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.UpdateUserRole")
    @ResponseWrapper(localName = "updateUserRoleResponse", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.UpdateUserRoleResponse")
    @Action(input = "http://controller.digipay.com/RoleController/updateUserRoleRequest", output = "http://controller.digipay.com/RoleController/updateUserRoleResponse")
    public void updateUserRole(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "removeUserRole", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.RemoveUserRole")
    @ResponseWrapper(localName = "removeUserRoleResponse", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.RemoveUserRoleResponse")
    @Action(input = "http://controller.digipay.com/RoleController/removeUserRoleRequest", output = "http://controller.digipay.com/RoleController/removeUserRoleResponse")
    public void removeUserRole(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

}
