
package com.digipay.employee;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "UserControllerImplService", targetNamespace = "http://impl.controller.digipay.com/", wsdlLocation = "http://localhost:8080/usermanagement/user?wsdl")
public class UserControllerImplService
    extends Service
{

    private final static URL USERCONTROLLERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERCONTROLLERIMPLSERVICE_EXCEPTION;
    private final static QName USERCONTROLLERIMPLSERVICE_QNAME = new QName("http://impl.controller.digipay.com/", "UserControllerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/usermanagement/user?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERCONTROLLERIMPLSERVICE_WSDL_LOCATION = url;
        USERCONTROLLERIMPLSERVICE_EXCEPTION = e;
    }

    public UserControllerImplService() {
        super(__getWsdlLocation(), USERCONTROLLERIMPLSERVICE_QNAME);
    }

    public UserControllerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERCONTROLLERIMPLSERVICE_QNAME, features);
    }

    public UserControllerImplService(URL wsdlLocation) {
        super(wsdlLocation, USERCONTROLLERIMPLSERVICE_QNAME);
    }

    public UserControllerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERCONTROLLERIMPLSERVICE_QNAME, features);
    }

    public UserControllerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserControllerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserController
     */
    @WebEndpoint(name = "UserControllerImplPort")
    public UserController getUserControllerImplPort() {
        return super.getPort(new QName("http://impl.controller.digipay.com/", "UserControllerImplPort"), UserController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserController
     */
    @WebEndpoint(name = "UserControllerImplPort")
    public UserController getUserControllerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.controller.digipay.com/", "UserControllerImplPort"), UserController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERCONTROLLERIMPLSERVICE_EXCEPTION!= null) {
            throw USERCONTROLLERIMPLSERVICE_EXCEPTION;
        }
        return USERCONTROLLERIMPLSERVICE_WSDL_LOCATION;
    }

}
