
package com.digipay.employee;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "UserController", targetNamespace = "http://controller.digipay.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserController {


    /**
     * 
     * @param nationalCode
     * @param roleId
     * @param userName
     */
    @WebMethod
    @RequestWrapper(localName = "saveUserInfo", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.SaveUserInfo")
    @ResponseWrapper(localName = "saveUserInfoResponse", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.SaveUserInfoResponse")
    @Action(input = "http://controller.digipay.com/UserController/saveUserInfoRequest", output = "http://controller.digipay.com/UserController/saveUserInfoResponse")
    public void saveUserInfo(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "nationalCode", targetNamespace = "")
        String nationalCode,
        @WebParam(name = "roleId", targetNamespace = "")
        List<String> roleId);

    /**
     * 
     * @return
     *     returns java.util.List<com.digipay.employee.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "displayUser", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.DisplayUser")
    @ResponseWrapper(localName = "displayUserResponse", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.DisplayUserResponse")
    @Action(input = "http://controller.digipay.com/UserController/displayUserRequest", output = "http://controller.digipay.com/UserController/displayUserResponse")
    public List<User> displayUser();

    /**
     * 
     * @param name
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.UpdateUserResponse")
    @Action(input = "http://controller.digipay.com/UserController/updateUserRequest", output = "http://controller.digipay.com/UserController/updateUserResponse")
    public void updateUser(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param nationalCode
     * @return
     *     returns com.digipay.employee.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserByNid", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.GetUserByNid")
    @ResponseWrapper(localName = "getUserByNidResponse", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.GetUserByNidResponse")
    @Action(input = "http://controller.digipay.com/UserController/getUserByNidRequest", output = "http://controller.digipay.com/UserController/getUserByNidResponse")
    public User getUserByNid(
        @WebParam(name = "nationalCode", targetNamespace = "")
        String nationalCode);

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "removeUser", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.RemoveUser")
    @ResponseWrapper(localName = "removeUserResponse", targetNamespace = "http://controller.digipay.com/", className = "com.digipay.employee.RemoveUserResponse")
    @Action(input = "http://controller.digipay.com/UserController/removeUserRequest", output = "http://controller.digipay.com/UserController/removeUserResponse")
    public void removeUser(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

}
